title: Notdemon.xyz | Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.notdemon.xyz
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: Gateway
      category: Gateways
    - name: Backup Gateway
      category: Gateways
    - name: Website
      description: The web frontend for the application.
      category: Germany
      link: https://chriswasntavailable.xyz/
    - name: API
      description: This Hasn't Been Developed Yet
      category: Germany
    - name: CDN / Media Proxie
      description: This is the service responsible for serving images, audio, and
        video. It is reliant on our CDN.
      category: Germany
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: /img/icon.gif
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: monthly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Germany
      description: The main servers are located here.
      closed: true
    - name: Gateways
    - name: Uncategorized
      untitled: true
  description: We continuously monitor the status of our services and if there are
    any interruptions, a note will be posted here.
  enableCustomHTML: true
  useLargeHeaderDesign: false
